#!/bin/bash
#SBATCH --nodes=1
#SBATCH --time=12:00:00
#SBATCH --job-name=EFICAz_SEQUENCE_FILENAME_X1

# Customize path to EFICAz.
EFICAz25_PATH=${HOME}/EFICAz2.5.1
export EFICAz25_PATH

module load NiaEnv/2018a;
module load anaconda2

# Go to directory with sequences
cd EFICAz

mkdir -p Results

# Customize path to RAMDISK.
local_path=/dev/shm/${USER}/EFICAz
(mkdir -p $local_path/SEQUENCE_FILENAME_X1; cat Split_seqs/SEQUENCE_FILENAME_X1 > $local_path/SEQUENCE_FILENAME_X1/SEQUENCE_FILENAME_X1; cd $local_path/SEQUENCE_FILENAME_X1; python $EFICAz25_PATH/bin/EFICAz_latest.py SEQUENCE_FILENAME_X1) &

(mkdir -p $local_path/SEQUENCE_FILENAME_X2; cat Split_seqs/SEQUENCE_FILENAME_X2 > $local_path/SEQUENCE_FILENAME_X2/SEQUENCE_FILENAME_X2; cd $local_path/SEQUENCE_FILENAME_X2; python $EFICAz25_PATH/bin/EFICAz_latest.py SEQUENCE_FILENAME_X2) &

(mkdir -p $local_path/SEQUENCE_FILENAME_X3; cat Split_seqs/SEQUENCE_FILENAME_X3 > $local_path/SEQUENCE_FILENAME_X3/SEQUENCE_FILENAME_X3; cd $local_path/SEQUENCE_FILENAME_X3; python $EFICAz25_PATH/bin/EFICAz_latest.py SEQUENCE_FILENAME_X3) &

(mkdir -p $local_path/SEQUENCE_FILENAME_X4; cat Split_seqs/SEQUENCE_FILENAME_X4 > $local_path/SEQUENCE_FILENAME_X4/SEQUENCE_FILENAME_X4; cd $local_path/SEQUENCE_FILENAME_X4; python $EFICAz25_PATH/bin/EFICAz_latest.py SEQUENCE_FILENAME_X4) &

(mkdir -p $local_path/SEQUENCE_FILENAME_X5; cat Split_seqs/SEQUENCE_FILENAME_X5 > $local_path/SEQUENCE_FILENAME_X5/SEQUENCE_FILENAME_X5; cd $local_path/SEQUENCE_FILENAME_X5; python $EFICAz25_PATH/bin/EFICAz_latest.py SEQUENCE_FILENAME_X5) &

(mkdir -p $local_path/SEQUENCE_FILENAME_X6; cat Split_seqs/SEQUENCE_FILENAME_X6 > $local_path/SEQUENCE_FILENAME_X6/SEQUENCE_FILENAME_X6; cd $local_path/SEQUENCE_FILENAME_X6; python $EFICAz25_PATH/bin/EFICAz_latest.py SEQUENCE_FILENAME_X6) &

(mkdir -p $local_path/SEQUENCE_FILENAME_X7; cat Split_seqs/SEQUENCE_FILENAME_X7 > $local_path/SEQUENCE_FILENAME_X7/SEQUENCE_FILENAME_X7; cd $local_path/SEQUENCE_FILENAME_X7; python $EFICAz25_PATH/bin/EFICAz_latest.py SEQUENCE_FILENAME_X7) &

(mkdir -p $local_path/SEQUENCE_FILENAME_X8; cat Split_seqs/SEQUENCE_FILENAME_X8 > $local_path/SEQUENCE_FILENAME_X8/SEQUENCE_FILENAME_X8; cd $local_path/SEQUENCE_FILENAME_X8; python $EFICAz25_PATH/bin/EFICAz_latest.py SEQUENCE_FILENAME_X8) &

(mkdir -p $local_path/SEQUENCE_FILENAME_X9; cat Split_seqs/SEQUENCE_FILENAME_X9 > $local_path/SEQUENCE_FILENAME_X9/SEQUENCE_FILENAME_X9; cd $local_path/SEQUENCE_FILENAME_X9; python $EFICAz25_PATH/bin/EFICAz_latest.py SEQUENCE_FILENAME_X9) &

(mkdir -p $local_path/SEQUENCE_FILENAME_10; cat Split_seqs/SEQUENCE_FILENAME_10 > $local_path/SEQUENCE_FILENAME_10/SEQUENCE_FILENAME_10; cd $local_path/SEQUENCE_FILENAME_10; python $EFICAz25_PATH/bin/EFICAz_latest.py SEQUENCE_FILENAME_10) &

(mkdir -p $local_path/SEQUENCE_FILENAME_11; cat Split_seqs/SEQUENCE_FILENAME_11 > $local_path/SEQUENCE_FILENAME_11/SEQUENCE_FILENAME_11; cd $local_path/SEQUENCE_FILENAME_11; python $EFICAz25_PATH/bin/EFICAz_latest.py SEQUENCE_FILENAME_11) &

(mkdir -p $local_path/SEQUENCE_FILENAME_12; cat Split_seqs/SEQUENCE_FILENAME_12 > $local_path/SEQUENCE_FILENAME_12/SEQUENCE_FILENAME_12; cd $local_path/SEQUENCE_FILENAME_12; python $EFICAz25_PATH/bin/EFICAz_latest.py SEQUENCE_FILENAME_12) &

(mkdir -p $local_path/SEQUENCE_FILENAME_13; cat Split_seqs/SEQUENCE_FILENAME_13 > $local_path/SEQUENCE_FILENAME_13/SEQUENCE_FILENAME_13; cd $local_path/SEQUENCE_FILENAME_13; python $EFICAz25_PATH/bin/EFICAz_latest.py SEQUENCE_FILENAME_13) &

(mkdir -p $local_path/SEQUENCE_FILENAME_14; cat Split_seqs/SEQUENCE_FILENAME_14 > $local_path/SEQUENCE_FILENAME_14/SEQUENCE_FILENAME_14; cd $local_path/SEQUENCE_FILENAME_14; python $EFICAz25_PATH/bin/EFICAz_latest.py SEQUENCE_FILENAME_14) &

(mkdir -p $local_path/SEQUENCE_FILENAME_15; cat Split_seqs/SEQUENCE_FILENAME_15 > $local_path/SEQUENCE_FILENAME_15/SEQUENCE_FILENAME_15; cd $local_path/SEQUENCE_FILENAME_15; python $EFICAz25_PATH/bin/EFICAz_latest.py SEQUENCE_FILENAME_15) &

(mkdir -p $local_path/SEQUENCE_FILENAME_16; cat Split_seqs/SEQUENCE_FILENAME_16 > $local_path/SEQUENCE_FILENAME_16/SEQUENCE_FILENAME_16; cd $local_path/SEQUENCE_FILENAME_16; python $EFICAz25_PATH/bin/EFICAz_latest.py SEQUENCE_FILENAME_16) &

(mkdir -p $local_path/SEQUENCE_FILENAME_17; cat Split_seqs/SEQUENCE_FILENAME_17 > $local_path/SEQUENCE_FILENAME_17/SEQUENCE_FILENAME_17; cd $local_path/SEQUENCE_FILENAME_17; python $EFICAz25_PATH/bin/EFICAz_latest.py SEQUENCE_FILENAME_17) &

(mkdir -p $local_path/SEQUENCE_FILENAME_18; cat Split_seqs/SEQUENCE_FILENAME_18 > $local_path/SEQUENCE_FILENAME_18/SEQUENCE_FILENAME_18; cd $local_path/SEQUENCE_FILENAME_18; python $EFICAz25_PATH/bin/EFICAz_latest.py SEQUENCE_FILENAME_18) &

(mkdir -p $local_path/SEQUENCE_FILENAME_19; cat Split_seqs/SEQUENCE_FILENAME_19 > $local_path/SEQUENCE_FILENAME_19/SEQUENCE_FILENAME_19; cd $local_path/SEQUENCE_FILENAME_19; python $EFICAz25_PATH/bin/EFICAz_latest.py SEQUENCE_FILENAME_19) &

(mkdir -p $local_path/SEQUENCE_FILENAME_20; cat Split_seqs/SEQUENCE_FILENAME_20 > $local_path/SEQUENCE_FILENAME_20/SEQUENCE_FILENAME_20; cd $local_path/SEQUENCE_FILENAME_20; python $EFICAz25_PATH/bin/EFICAz_latest.py SEQUENCE_FILENAME_20) &

(mkdir -p $local_path/SEQUENCE_FILENAME_21; cat Split_seqs/SEQUENCE_FILENAME_21 > $local_path/SEQUENCE_FILENAME_21/SEQUENCE_FILENAME_21; cd $local_path/SEQUENCE_FILENAME_21; python $EFICAz25_PATH/bin/EFICAz_latest.py SEQUENCE_FILENAME_21) &

(mkdir -p $local_path/SEQUENCE_FILENAME_22; cat Split_seqs/SEQUENCE_FILENAME_22 > $local_path/SEQUENCE_FILENAME_22/SEQUENCE_FILENAME_22; cd $local_path/SEQUENCE_FILENAME_22; python $EFICAz25_PATH/bin/EFICAz_latest.py SEQUENCE_FILENAME_22) &

(mkdir -p $local_path/SEQUENCE_FILENAME_23; cat Split_seqs/SEQUENCE_FILENAME_23 > $local_path/SEQUENCE_FILENAME_23/SEQUENCE_FILENAME_23; cd $local_path/SEQUENCE_FILENAME_23; python $EFICAz25_PATH/bin/EFICAz_latest.py SEQUENCE_FILENAME_23) &

(mkdir -p $local_path/SEQUENCE_FILENAME_24; cat Split_seqs/SEQUENCE_FILENAME_24 > $local_path/SEQUENCE_FILENAME_24/SEQUENCE_FILENAME_24; cd $local_path/SEQUENCE_FILENAME_24; python $EFICAz25_PATH/bin/EFICAz_latest.py SEQUENCE_FILENAME_24) &

(mkdir -p $local_path/SEQUENCE_FILENAME_25; cat Split_seqs/SEQUENCE_FILENAME_25 > $local_path/SEQUENCE_FILENAME_25/SEQUENCE_FILENAME_25; cd $local_path/SEQUENCE_FILENAME_25; python $EFICAz25_PATH/bin/EFICAz_latest.py SEQUENCE_FILENAME_25) &

(mkdir -p $local_path/SEQUENCE_FILENAME_26; cat Split_seqs/SEQUENCE_FILENAME_26 > $local_path/SEQUENCE_FILENAME_26/SEQUENCE_FILENAME_26; cd $local_path/SEQUENCE_FILENAME_26; python $EFICAz25_PATH/bin/EFICAz_latest.py SEQUENCE_FILENAME_26) &

(mkdir -p $local_path/SEQUENCE_FILENAME_27; cat Split_seqs/SEQUENCE_FILENAME_27 > $local_path/SEQUENCE_FILENAME_27/SEQUENCE_FILENAME_27; cd $local_path/SEQUENCE_FILENAME_27; python $EFICAz25_PATH/bin/EFICAz_latest.py SEQUENCE_FILENAME_27) &

(mkdir -p $local_path/SEQUENCE_FILENAME_28; cat Split_seqs/SEQUENCE_FILENAME_28 > $local_path/SEQUENCE_FILENAME_28/SEQUENCE_FILENAME_28; cd $local_path/SEQUENCE_FILENAME_28; python $EFICAz25_PATH/bin/EFICAz_latest.py SEQUENCE_FILENAME_28) &

(mkdir -p $local_path/SEQUENCE_FILENAME_29; cat Split_seqs/SEQUENCE_FILENAME_29 > $local_path/SEQUENCE_FILENAME_29/SEQUENCE_FILENAME_29; cd $local_path/SEQUENCE_FILENAME_29; python $EFICAz25_PATH/bin/EFICAz_latest.py SEQUENCE_FILENAME_29) &

(mkdir -p $local_path/SEQUENCE_FILENAME_30; cat Split_seqs/SEQUENCE_FILENAME_30 > $local_path/SEQUENCE_FILENAME_30/SEQUENCE_FILENAME_30; cd $local_path/SEQUENCE_FILENAME_30; python $EFICAz25_PATH/bin/EFICAz_latest.py SEQUENCE_FILENAME_30) &

(mkdir -p $local_path/SEQUENCE_FILENAME_31; cat Split_seqs/SEQUENCE_FILENAME_31 > $local_path/SEQUENCE_FILENAME_31/SEQUENCE_FILENAME_31; cd $local_path/SEQUENCE_FILENAME_31; python $EFICAz25_PATH/bin/EFICAz_latest.py SEQUENCE_FILENAME_31) &

(mkdir -p $local_path/SEQUENCE_FILENAME_32; cat Split_seqs/SEQUENCE_FILENAME_32 > $local_path/SEQUENCE_FILENAME_32/SEQUENCE_FILENAME_32; cd $local_path/SEQUENCE_FILENAME_32; python $EFICAz25_PATH/bin/EFICAz_latest.py SEQUENCE_FILENAME_32) &

(mkdir -p $local_path/SEQUENCE_FILENAME_33; cat Split_seqs/SEQUENCE_FILENAME_33 > $local_path/SEQUENCE_FILENAME_33/SEQUENCE_FILENAME_33; cd $local_path/SEQUENCE_FILENAME_33; python $EFICAz25_PATH/bin/EFICAz_latest.py SEQUENCE_FILENAME_33) &

(mkdir -p $local_path/SEQUENCE_FILENAME_34; cat Split_seqs/SEQUENCE_FILENAME_34 > $local_path/SEQUENCE_FILENAME_34/SEQUENCE_FILENAME_34; cd $local_path/SEQUENCE_FILENAME_34; python $EFICAz25_PATH/bin/EFICAz_latest.py SEQUENCE_FILENAME_34) &

(mkdir -p $local_path/SEQUENCE_FILENAME_35; cat Split_seqs/SEQUENCE_FILENAME_35 > $local_path/SEQUENCE_FILENAME_35/SEQUENCE_FILENAME_35; cd $local_path/SEQUENCE_FILENAME_35; python $EFICAz25_PATH/bin/EFICAz_latest.py SEQUENCE_FILENAME_35) &

(mkdir -p $local_path/SEQUENCE_FILENAME_36; cat Split_seqs/SEQUENCE_FILENAME_36 > $local_path/SEQUENCE_FILENAME_36/SEQUENCE_FILENAME_36; cd $local_path/SEQUENCE_FILENAME_36; python $EFICAz25_PATH/bin/EFICAz_latest.py SEQUENCE_FILENAME_36) &

(mkdir -p $local_path/SEQUENCE_FILENAME_37; cat Split_seqs/SEQUENCE_FILENAME_37 > $local_path/SEQUENCE_FILENAME_37/SEQUENCE_FILENAME_37; cd $local_path/SEQUENCE_FILENAME_37; python $EFICAz25_PATH/bin/EFICAz_latest.py SEQUENCE_FILENAME_37) &

(mkdir -p $local_path/SEQUENCE_FILENAME_38; cat Split_seqs/SEQUENCE_FILENAME_38 > $local_path/SEQUENCE_FILENAME_38/SEQUENCE_FILENAME_38; cd $local_path/SEQUENCE_FILENAME_38; python $EFICAz25_PATH/bin/EFICAz_latest.py SEQUENCE_FILENAME_38) &

(mkdir -p $local_path/SEQUENCE_FILENAME_39; cat Split_seqs/SEQUENCE_FILENAME_39 > $local_path/SEQUENCE_FILENAME_39/SEQUENCE_FILENAME_39; cd $local_path/SEQUENCE_FILENAME_39; python $EFICAz25_PATH/bin/EFICAz_latest.py SEQUENCE_FILENAME_39) &

(mkdir -p $local_path/SEQUENCE_FILENAME_40; cat Split_seqs/SEQUENCE_FILENAME_40 > $local_path/SEQUENCE_FILENAME_40/SEQUENCE_FILENAME_40; cd $local_path/SEQUENCE_FILENAME_40; python $EFICAz25_PATH/bin/EFICAz_latest.py SEQUENCE_FILENAME_40) &


wait

function save_results {  
	# Customise full path to desired folder to contain results.
	my_scratch=EFICAz/Results
	cd ${local_path}
    tar -czf SEQUENCE_FILENAME_X1.tar SEQUENCE_FILENAME_X1/*
	tar -czf SEQUENCE_FILENAME_X2.tar SEQUENCE_FILENAME_X2/*
	tar -czf SEQUENCE_FILENAME_X3.tar SEQUENCE_FILENAME_X3/*
	tar -czf SEQUENCE_FILENAME_X4.tar SEQUENCE_FILENAME_X4/*
	tar -czf SEQUENCE_FILENAME_X5.tar SEQUENCE_FILENAME_X5/*
	tar -czf SEQUENCE_FILENAME_X6.tar SEQUENCE_FILENAME_X6/*
	tar -czf SEQUENCE_FILENAME_X7.tar SEQUENCE_FILENAME_X7/*
	tar -czf SEQUENCE_FILENAME_X8.tar SEQUENCE_FILENAME_X8/*
    tar -czf SEQUENCE_FILENAME_X9.tar SEQUENCE_FILENAME_X9/*
	tar -czf SEQUENCE_FILENAME_10.tar SEQUENCE_FILENAME_10/*
	tar -czf SEQUENCE_FILENAME_11.tar SEQUENCE_FILENAME_11/*
	tar -czf SEQUENCE_FILENAME_12.tar SEQUENCE_FILENAME_12/*
	tar -czf SEQUENCE_FILENAME_13.tar SEQUENCE_FILENAME_13/*
	tar -czf SEQUENCE_FILENAME_14.tar SEQUENCE_FILENAME_14/*
	tar -czf SEQUENCE_FILENAME_15.tar SEQUENCE_FILENAME_15/*
	tar -czf SEQUENCE_FILENAME_16.tar SEQUENCE_FILENAME_16/*
    tar -czf SEQUENCE_FILENAME_17.tar SEQUENCE_FILENAME_17/*
	tar -czf SEQUENCE_FILENAME_18.tar SEQUENCE_FILENAME_18/*
	tar -czf SEQUENCE_FILENAME_19.tar SEQUENCE_FILENAME_19/*
	tar -czf SEQUENCE_FILENAME_20.tar SEQUENCE_FILENAME_20/*
	tar -czf SEQUENCE_FILENAME_21.tar SEQUENCE_FILENAME_21/*
	tar -czf SEQUENCE_FILENAME_22.tar SEQUENCE_FILENAME_22/*
	tar -czf SEQUENCE_FILENAME_23.tar SEQUENCE_FILENAME_23/*
	tar -czf SEQUENCE_FILENAME_24.tar SEQUENCE_FILENAME_24/*
    tar -czf SEQUENCE_FILENAME_25.tar SEQUENCE_FILENAME_25/*
	tar -czf SEQUENCE_FILENAME_26.tar SEQUENCE_FILENAME_26/*
	tar -czf SEQUENCE_FILENAME_27.tar SEQUENCE_FILENAME_27/*
	tar -czf SEQUENCE_FILENAME_28.tar SEQUENCE_FILENAME_28/*
	tar -czf SEQUENCE_FILENAME_29.tar SEQUENCE_FILENAME_29/*
	tar -czf SEQUENCE_FILENAME_30.tar SEQUENCE_FILENAME_30/*
	tar -czf SEQUENCE_FILENAME_31.tar SEQUENCE_FILENAME_31/*
	tar -czf SEQUENCE_FILENAME_32.tar SEQUENCE_FILENAME_32/*
    tar -czf SEQUENCE_FILENAME_33.tar SEQUENCE_FILENAME_33/*
	tar -czf SEQUENCE_FILENAME_34.tar SEQUENCE_FILENAME_34/*
	tar -czf SEQUENCE_FILENAME_35.tar SEQUENCE_FILENAME_35/*
	tar -czf SEQUENCE_FILENAME_36.tar SEQUENCE_FILENAME_36/*
	tar -czf SEQUENCE_FILENAME_37.tar SEQUENCE_FILENAME_37/*
	tar -czf SEQUENCE_FILENAME_38.tar SEQUENCE_FILENAME_38/*
	tar -czf SEQUENCE_FILENAME_39.tar SEQUENCE_FILENAME_39/*
	tar -czf SEQUENCE_FILENAME_40.tar SEQUENCE_FILENAME_40/*
	
    cp SEQUENCE_FILENAME_X1.tar ${my_scratch}/SEQUENCE_FILENAME_X1.tar
	cp SEQUENCE_FILENAME_X2.tar ${my_scratch}/SEQUENCE_FILENAME_X2.tar
	cp SEQUENCE_FILENAME_X3.tar ${my_scratch}/SEQUENCE_FILENAME_X3.tar
	cp SEQUENCE_FILENAME_X4.tar ${my_scratch}/SEQUENCE_FILENAME_X4.tar
    cp SEQUENCE_FILENAME_X5.tar ${my_scratch}/SEQUENCE_FILENAME_X5.tar
	cp SEQUENCE_FILENAME_X6.tar ${my_scratch}/SEQUENCE_FILENAME_X6.tar
	cp SEQUENCE_FILENAME_X7.tar ${my_scratch}/SEQUENCE_FILENAME_X7.tar
	cp SEQUENCE_FILENAME_X8.tar ${my_scratch}/SEQUENCE_FILENAME_X8.tar
    cp SEQUENCE_FILENAME_X9.tar ${my_scratch}/SEQUENCE_FILENAME_X9.tar
	cp SEQUENCE_FILENAME_10.tar ${my_scratch}/SEQUENCE_FILENAME_10.tar
	cp SEQUENCE_FILENAME_11.tar ${my_scratch}/SEQUENCE_FILENAME_11.tar
	cp SEQUENCE_FILENAME_12.tar ${my_scratch}/SEQUENCE_FILENAME_12.tar
    cp SEQUENCE_FILENAME_13.tar ${my_scratch}/SEQUENCE_FILENAME_13.tar
	cp SEQUENCE_FILENAME_14.tar ${my_scratch}/SEQUENCE_FILENAME_14.tar
	cp SEQUENCE_FILENAME_15.tar ${my_scratch}/SEQUENCE_FILENAME_15.tar
	cp SEQUENCE_FILENAME_16.tar ${my_scratch}/SEQUENCE_FILENAME_16.tar
    cp SEQUENCE_FILENAME_17.tar ${my_scratch}/SEQUENCE_FILENAME_17.tar
	cp SEQUENCE_FILENAME_18.tar ${my_scratch}/SEQUENCE_FILENAME_18.tar
	cp SEQUENCE_FILENAME_19.tar ${my_scratch}/SEQUENCE_FILENAME_19.tar
	cp SEQUENCE_FILENAME_20.tar ${my_scratch}/SEQUENCE_FILENAME_20.tar
    cp SEQUENCE_FILENAME_21.tar ${my_scratch}/SEQUENCE_FILENAME_21.tar
	cp SEQUENCE_FILENAME_22.tar ${my_scratch}/SEQUENCE_FILENAME_22.tar
	cp SEQUENCE_FILENAME_23.tar ${my_scratch}/SEQUENCE_FILENAME_23.tar
	cp SEQUENCE_FILENAME_24.tar ${my_scratch}/SEQUENCE_FILENAME_24.tar
    cp SEQUENCE_FILENAME_25.tar ${my_scratch}/SEQUENCE_FILENAME_25.tar
	cp SEQUENCE_FILENAME_26.tar ${my_scratch}/SEQUENCE_FILENAME_26.tar
	cp SEQUENCE_FILENAME_27.tar ${my_scratch}/SEQUENCE_FILENAME_27.tar
	cp SEQUENCE_FILENAME_28.tar ${my_scratch}/SEQUENCE_FILENAME_28.tar
    cp SEQUENCE_FILENAME_29.tar ${my_scratch}/SEQUENCE_FILENAME_29.tar
	cp SEQUENCE_FILENAME_30.tar ${my_scratch}/SEQUENCE_FILENAME_30.tar
	cp SEQUENCE_FILENAME_31.tar ${my_scratch}/SEQUENCE_FILENAME_31.tar
	cp SEQUENCE_FILENAME_32.tar ${my_scratch}/SEQUENCE_FILENAME_32.tar
    cp SEQUENCE_FILENAME_33.tar ${my_scratch}/SEQUENCE_FILENAME_33.tar
	cp SEQUENCE_FILENAME_34.tar ${my_scratch}/SEQUENCE_FILENAME_34.tar
	cp SEQUENCE_FILENAME_35.tar ${my_scratch}/SEQUENCE_FILENAME_35.tar
	cp SEQUENCE_FILENAME_36.tar ${my_scratch}/SEQUENCE_FILENAME_36.tar
    cp SEQUENCE_FILENAME_37.tar ${my_scratch}/SEQUENCE_FILENAME_37.tar
	cp SEQUENCE_FILENAME_38.tar ${my_scratch}/SEQUENCE_FILENAME_38.tar
	cp SEQUENCE_FILENAME_39.tar ${my_scratch}/SEQUENCE_FILENAME_39.tar
	cp SEQUENCE_FILENAME_40.tar ${my_scratch}/SEQUENCE_FILENAME_40.tar
	
}

function cleanup_ramdisk {
    echo "Cleaning up ramdisk directory /dev/shm/${USER}/EFICAz"
    rm -rf $local_path
    echo "done"
}

save_results

date

#Done
cleanup_ramdisk

date